<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>东营时空邮局 - 寄语未来</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/guestbook_style.css">
</head>
<body class="light-theme">

    <jsp:include page="header.jspf"/>

    <main class="gb-main-container">

        <!-- Module 1: The Curator's Letter -->
        <header class="gb-header">
            <div class="gb-header-content">
                <h1 class="gb-title">东营时空邮局</h1>
                <p id="gb-typewriter-subtitle" class="gb-subtitle">每一封信，都是时间写给未来的诗</p>
                <div class="gb-intro-text">
                    <p>欢迎来到东营时空邮局。这里不是一座普通的建筑，而是一个时间的容器，一个记忆的避风港。自第一缕晨光亲吻黄河三角洲的年轻湿地，自第一座井架在渤海之滨拔地而起，这里便开始静静收集散落在风中的故事、低语和梦想。我们相信，每一座城市都有其独特的脉搏，每一次心跳都值得被记录。东营，这座在河海交汇处诞生的奇迹之城，它的故事更是波澜壮阔，却又由无数平凡而深刻的瞬间构成。</p>
                    <p>这座邮局的"局长"，是一位虚构的、热爱聆听的老者。他穷尽一生，试图捕捉那些瞬息即逝的情感。他看到过勘探队员在星光下写给家人的信，字里行间是对未来的憧憬和对亲人的思念；他听到过稻香蟹肥时节，田埂上农人满足的哼唱；他感受到新生儿的第一声啼哭，如何与这座城市的轰鸣交织成最动人的交响。他设立这座邮局，不为传递实体的信件，只为封存这些无形的、珍贵的精神财富。</p>
                    <p>在这里，您既是读者，也是作者。您可以漫步于下方的"时光回音廊"，那里陈列着来自过去旅客的"明信片"。每一次点击翻阅，都是一次与陌生灵魂的隔空对话。您会发现，尽管时空变幻，但人类共通的情感——喜悦、思索、怀念、期盼——却恒久不变，如夜空中的星辰，永远在那里闪烁。当您准备好，我们诚挚地邀请您走向"未来书写台"，亲手写下属于您的那一笔。它或许是对东营的祝福，或许是对某个人的悄悄话，又或许只是记录下此刻稍纵即逝的心情。请放心，您的文字将被妥善保管，成为这片数字时空里永恒的一部分，等待未来的某个"旅行者"不期而遇。现在，请开始您的时空之旅吧。</p>
                </div>
            </div>
        </header>

        <!-- Module 2: The Data Pavilion (NEW) -->
        <section class="gb-data-pavilion">
            <div class="gb-data-summary">
                <p id="gb-summary-text">正在分析时空数据...</p>
            </div>
            <div id="gb-data-chart" class="gb-data-chart">
                <!-- Interactive CSS chart will be generated by JS here -->
            </div>
        </section>

        <!-- Module 3: The Echo Gallery (Renumbered) -->
        <section class="gb-gallery-wrapper">
            <div class="gb-gallery-controls">
                <div class="gb-gallery-filters">
                    <input type="text" id="gb-search-box" placeholder="按昵称搜索信笺...">
                    <select id="gb-sort-select">
                        <option value="newest">按时间（最新）</option>
                        <option value="oldest">按时间（最早）</option>
                    </select>
                </div>
                <%-- The old emotion filter bar is now removed and replaced by the chart --%>
            </div>
            <div id="gb-gallery" class="gb-gallery">
                <!-- Messages are now simplified for modal interaction -->
                <c:forEach var="msg" items="${messages}">
                    <div class="gb-postcard" 
                         data-nickname="${msg.nickname}" 
                         data-timestamp="${msg.timestamp}" 
                         data-emotion="${msg.emotionTag}"
                         data-content="${msg.content}">
                        <span class="gb-postcard-emotion">${msg.emotionTag}</span>
                        <p class="gb-postcard-recipient">To: 未来的某个你</p>
                        <p class="gb-postcard-author">From: ${msg.nickname}</p>
                    </div>
                </c:forEach>
            </div>
        </section>

        <!-- Module 4: The Scriptorium (The Form) -->
        <section class="gb-form-wrapper">
            <div class="gb-form-container">
                <h2>未来书写台</h2>
                <p>在此留下您的印记，它将被时间珍藏。</p>
                <form id="gb-form" action="guestbook" method="post" novalidate>
                    <div class="form-group floating-label-group">
                        <input type="text" id="gb-nickname" name="nickname" class="form-control" placeholder=" " required>
                        <label for="gb-nickname">您的"执笔人"署名</label>
                    </div>
                    <div class="form-group floating-label-group">
                        <textarea id="gb-content" name="content" class="form-control" rows="6" placeholder=" " required maxlength="280"></textarea>
                        <label for="gb-content">信笺内容</label>
                        <div class="char-counter-container">
                            <span id="char-counter">0</span>/280
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="static-label">为此刻的心情盖上邮戳</label>
                        <div class="gb-emotion-selector">
                            <span class="gb-emotion-option selected" data-emotion="开心">开心</span>
                            <span class="gb-emotion-option" data-emotion="灵感">灵感</span>
                            <span class="gb-emotion-option" data-emotion="思考">思考</span>
                            <span class="gb-emotion-option" data-emotion="希望">希望</span>
                            <span class="gb-emotion-option" data-emotion="祝福">祝福</span>
                            <span class="gb-emotion-option" data-emotion="行者">行者</span>
                            <span class="gb-emotion-option" data-emotion="怀旧">怀旧</span>
                            <span class="gb-emotion-option" data-emotion="奋斗">奋斗</span>
                            <span class="gb-emotion-option" data-emotion="收获">收获</span>
                            <span class="gb-emotion-option" data-emotion="乡愁">乡愁</span>
                            <span class="gb-emotion-option" data-emotion="瞬间">瞬间</span>
                            <span class="gb-emotion-option" data-emotion="约定">约定</span>
                        </div>
                        <input type="hidden" id="gb-emotion-value" name="emotionTag" value="开心">
                    </div>
                    <button type="submit" class="gb-submit-btn">投递到未来</button>
                </form>
            </div>
        </section>

        <!-- Module 5: The Dusty Archives (Restored & Expanded) -->
        <section class="gb-archives-wrapper">
            <h2>尘封的档案</h2>
            <div class="gb-accordion">
                <div class="gb-accordion-item">
                    <button class="gb-accordion-header">
                        <h3>档案一：黄河的信使</h3>
                        <span class="gb-accordion-icon">+</span>
                    </button>
                    <div class="gb-accordion-content">
                        <div class="gb-accordion-content-inner">
                            <p>在东营这片由黄河泥沙冲积而成的年轻土地上，"通信"一词有着非凡的重量。它不仅是信息的传递，更是文明与存在的证明。远在文字诞生之前，黄河本身就是最原始的"信使"。它的每一次改道，每一次泛滥，都像一封封厚重的信件，用最磅礴的笔触，书写着大地的变迁，决定着聚落的兴衰。河流的走向、水量的多寡，是沿岸先民赖以生存的密码，他们学会了阅读这封"无字之书"，逐水草而居，依天时而作，完成了最早的人与自然的对话。</p>
                            <p>随着丝绸之路的延伸和漕运的繁忙，更为精细的通信方式开始出现。驿站制度，如同一张巨大的网络，将东营及其周边区域纳入了帝国的神经系统。驿卒们策马扬鞭，日夜兼程，传递着公文、军令和商报。马蹄踏过古老的河道，激起的尘土里，混合着汗水与使命感。他们是移动的"信使"，连接着中枢与边陲，维系着庞大帝国的运转。</p>
                            <p>进入近代，电报和电话的出现，是通信史上的一次革命。滴滴答答的电码，第一次让信息的速度超越了马匹。在东营，尤其是在胜利油田的勘探开发初期，通信的重要性被提到了前所未有的高度。电话线和电报线，就像是现代文明的血管，被铺设到一个个钻井平台和生活基地，为这座新兴的工业城市注入了生命力。这些线路传递的，不再仅仅是家国大事，更多的是生产的指令、技术的参数，是科学与效率的语言。</p>
                        </div>
                    </div>
                </div>
                <div class="gb-accordion-item">
                    <button class="gb-accordion-header">
                        <h3>档案二：油田的家书</h3>
                        <span class="gb-accordion-icon">+</span>
                    </button>
                    <div class="gb-accordion-content">
                        <div class="gb-accordion-content-inner">
                            <p>胜利油田的发现与建设，是共和国历史上的一座丰碑，也是无数家庭奉献与牺牲的集体记忆。在那个激情燃烧又物质匮乏的年代，家书，是连接广阔荒原上的石油会战现场与遥远故乡的唯一纽带。它不仅仅是纸上的文字，更是精神的食粮，是支撑一代石油人在艰苦环境中坚持下去的重要力量。</p>
                            <p>"亲爱的秀英，"一封泛黄的信纸上这样写道，"此地风沙极大，张口就是一嘴沙子，但我们心里是甜的。昨夜，三号井终于出油了，黑色的'金子'喷涌而出时，所有人都像孩子一样又笑又跳，把帽子抛到了天上。我看见王师傅，一个五十多岁的硬汉，背过身去偷偷抹眼泪。你或许无法想象那种场面，那感觉，我们不是在为自己，是在为国家'加油'啊。勿念，照顾好孩子和老人。"</p>
                            <p>这些家书，记录的不仅仅是工作与生活。它们是历史的细节，是宏大叙事下最生动的个人注脚。信中会提到第一次看到渤海的感觉，会描述第一次吃到海鲜的惊喜，会讨论某部新上映的电影《创业》，也会交流孩子的学习成绩。这些琐碎而真实的片段，共同构建了胜利油田早期生活的全貌。</p>
                        </div>
                    </div>
                </div>
                <div class="gb-accordion-item">
                    <button class="gb-accordion-header">
                        <h3>档案三：河口的絮语</h3>
                        <span class="gb-accordion-icon">+</span>
                    </button>
                    <div class="gb-accordion-content">
                        <div class="gb-accordion-content-inner">
                            <p>如果说，黄河的信件是用泥沙书写的史诗，油田的家书是蘸着热血谱写的奉献，那么河口的絮语，则是风与芦苇的低吟，是水鸟与潮汐的对白。这是东营最宁静、最富诗意的一封信，写给所有愿意倾听自然的人。</p>
                            <p>这里的每一寸土地都无比年轻。黄河，这位不知疲倦的母亲，每年仍在这里创造着数万亩的新生土地。站在这片土地上，你能真实地感受到"沧海桑田"不是一个遥远的神话，而是一个正在眼前发生的地理奇迹。春天，新生的碱蓬草为大地铺上红色的地毯，那是地球写给天空最热烈的情书；秋天，一望无际的芦花随风摇曳，如白色的波浪，那是风在诉说着远方的故事。</p>
                            <p>这里是鸟类的天堂，是国际重要的鸟类迁徙中转站。每年，数百万只候鸟在此停歇、繁殖、越冬。它们是最高级的"信使"，携带着不同纬度的气候信息和生命密码。当优雅的丹顶鹤展开翅膀，当成群的东方白鹳翩翩起舞，它们不仅构成了一幅绝美的生态画卷，更是在无声地宣告：这片土地的生态系统是健康的、充满活力的。它们的每一次鸣叫，都是对这片新生湿地最权威的"认证"。</p>
                            <p>人与自然的关系在这里被重新定义。不再是征服与索取，更多的是守护与共生。当地的渔民学会了遵循潮汐的规律，在不打扰鸟类栖息的前提下进行捕捞。生态旅游的开发者们，则小心翼翼地修建木栈道，引导游客在最小干预的范围内，欣赏这片自然的奇迹。这里的"絮语"，教会了我们一种更谦逊、更智慧的相处之道。它告诉我们，最深刻的交流，有时并不需要语言，一个眼神，一阵风，一声鸟鸣，足矣。</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Module 5: The Spotlight Modal (NEW) -->
        <div id="gb-spotlight-modal" class="gb-spotlight-modal">
            <div class="gb-modal-overlay"></div>
            <div class="gb-modal-content">
                <button id="gb-modal-close" class="gb-modal-close-btn">&times;</button>
                <div class="gb-modal-header">
                    <span id="modal-emotion-tag" class="gb-modal-emotion"></span>
                    <p>来自 <strong id="modal-nickname"></strong> 的信笺</p>
                </div>
                <div id="modal-message-content" class="gb-modal-body">
                    <!-- Message content goes here -->
                </div>
                <div class="gb-modal-footer">
                    <p>投递于 <span id="modal-timestamp"></span></p>
                </div>
            </div>
        </div>

    </main>

    <jsp:include page="/WEB-INF/jspf/footer.jspf" />

    <script src="js/guestbook_app.js"></script>
</body>
</html> 